web:
  build: .
  links:
    - mongo
  ports:
    - "8080:8080"
  volumes:
    - .:/application
  working_dir: /application
  command: bash -c 'npm install && npm start'
  environment:
    NODE_ENV: development

test:
  build: .
  links:
    - mongo
  volumes:
    - .:/application
  working_dir: /application
  command: bash -c 'npm install && npm test'
  environment:
    NODE_ENV: test

mongo:
  image: mongo
